import { createHash } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import { createDatabase, LOCAL_TEST_DATABASE_URL } from '@/db/client';
import { isAuthorizedOwner } from '@/features/admin/owner-auth';
import { normalizeAnchors, plainText, type DechiveDocument } from '@/features/editor-lab/document';
import { validateDechiveDocument } from '@/features/editor-lab/security';

export type OfficialSource={title:string;url:string};
export type AiUpdateDraftInput={title:string;slug:string;locale:'ko'|'en';summary:string;officialUpdatedAt:string;lastVerifiedAt:string;officialSources:OfficialSource[];document:DechiveDocument};
export type AiUpdateDraft=AiUpdateDraftInput&{localizationId:string;contentId:string;versionId:string;versionNumber:number;route:string;updatedAt:string};
export type AiUpdatePublishState={draftVersionId:string;draftVersionNumber:number;publishedVersionId:string|null;publishedVersionNumber:number|null;readiness:ReturnType<typeof validateAiUpdatePublishReadiness>};
const slugPattern=/^[a-z0-9]+(?:-[a-z0-9]+)*$/; const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
export const aiUpdateCanonicalRoute=(slug:string)=>`/ai-update/${slug}`;
export function createAiUpdateAdminDatabase(){return createDatabase()} export function createLocalAiUpdateDatabase(){return createDatabase(LOCAL_TEST_DATABASE_URL)}
function date(value:string,name:string){if(!value.trim())return '';const parsed=new Date(value);if(Number.isNaN(parsed.getTime()))throw new Error(`${name}_invalid`);return parsed.toISOString()}
export function normalizeOfficialSources(sources:OfficialSource[]){const seen=new Set<string>();return sources.map(source=>({title:source.title.trim(),url:source.url.trim()})).filter(source=>source.title||source.url).map(source=>{if(!source.title)throw new Error('official_source_title_required');try{const url=new URL(source.url);if(!['http:','https:'].includes(url.protocol))throw new Error()}catch{throw new Error('official_source_url_invalid')}if(seen.has(source.url))throw new Error('official_source_url_duplicate');seen.add(source.url);return source})}
function normalize(raw:AiUpdateDraftInput){const title=raw.title.trim(),slug=raw.slug.trim(),summary=raw.summary.trim();if(!title)throw new Error('title_required');if(!slugPattern.test(slug))throw new Error('slug_invalid');if(!summary)throw new Error('summary_required');const officialUpdatedAt=date(raw.officialUpdatedAt,'official_updated_at'),lastVerifiedAt=date(raw.lastVerifiedAt,'last_verified_at');if(new Date(lastVerifiedAt)>new Date(Date.now()+60_000))throw new Error('last_verified_at_future');const document=normalizeAnchors(raw.document);const validation=validateDechiveDocument(document,'draft');if(validation.status==='rejected')throw new Error('document_invalid');return {title,slug,summary,officialUpdatedAt,lastVerifiedAt,officialSources:normalizeOfficialSources(raw.officialSources),document,validation,status:validation.status==='needs_review'?'needs_review':'draft' as const,locale:raw.locale}}
export function validateAiUpdatePublishReadiness(raw:AiUpdateDraftInput){const errors:string[]=[];let input:ReturnType<typeof normalize>|undefined;try{input=normalize(raw)}catch(error){errors.push(error instanceof Error?error.message:'ai_update_invalid')}if(input){if(!input.officialUpdatedAt)errors.push('official_updated_at_required');if(!input.lastVerifiedAt)errors.push('last_verified_at_required');if(!input.officialSources.length)errors.push('official_sources_required');if(!plainText(input.document))errors.push('body_required');errors.push(...validateDechiveDocument(input.document,'publish').issues.filter(issue=>issue.severity==='error'||issue.severity==='review').map(issue=>issue.code))}return {blockingErrors:[...new Set(errors)],warnings:[],ready:errors.length===0}}
async function transaction<T>(pool:Pool,run:(tx:PoolClient)=>Promise<T>){const tx=await pool.connect();try{await tx.query('BEGIN');const value=await run(tx);await tx.query('COMMIT');return value}catch(error){await tx.query('ROLLBACK');throw error}finally{tx.release()}}
async function owner(tx:PoolClient,actorId:string){if(!(await isAuthorizedOwner(tx,actorId)))throw new Error('admin_access_denied')}
async function saveVersion(tx:PoolClient,id:string,input:ReturnType<typeof normalize>,actorId:string,current:string|null){const versionNumber=Number((await tx.query(`SELECT coalesce(max(version_number),0)+1 AS next FROM content_versions WHERE localization_id=$1`,[id])).rows[0].next);const metadata={aiUpdate:{title:input.title,slug:input.slug,summary:input.summary,officialUpdatedAt:input.officialUpdatedAt,lastVerifiedAt:input.lastVerifiedAt,officialSources:input.officialSources}};const versionId=(await tx.query<{id:string}>(`INSERT INTO content_versions(localization_id,version_number,schema_version,canonical_document,status,revision_summary,changed_fields,created_by,supersedes_version_id,migration_metadata,document_checksum,validation_status,validation_warnings) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id`,[id,versionNumber,input.document.schemaVersion,input.document,input.status,`ai update draft ${versionNumber===1?'created':'revised'}`,JSON.stringify(['title','slug','summary','officialUpdatedAt','lastVerifiedAt','officialSources','body']),actorId,current,metadata,hash(input.document),input.validation.status,JSON.stringify(input.validation.issues.map(issue=>issue.code))])).rows[0]!.id;return {versionId,versionNumber}}
async function finalize(tx:PoolClient,id:string,input:ReturnType<typeof normalize>,actorId:string,current:string|null){const version=await saveVersion(tx,id,input,actorId,current);const route=aiUpdateCanonicalRoute(input.slug);if((await tx.query(`SELECT 1 FROM content_routes WHERE route=$1 AND localization_id<>$2 AND active_until IS NULL`,[route,id])).rowCount)throw new Error('route_conflict');await tx.query(`UPDATE content_localizations SET title=$1,summary=$2,slug=$3,current_draft_version_id=$4,updated_at=now() WHERE id=$5`,[input.title,input.summary,input.slug,version.versionId,id]);if(current)await tx.query(`UPDATE content_routes SET route=$1 WHERE localization_id=$2 AND is_canonical AND active_until IS NULL`,[route,id]);else await tx.query(`INSERT INTO content_routes(localization_id,route,route_type,is_canonical) VALUES($1,$2,'cms_draft',true)`,[id,route]);await tx.query(`INSERT INTO revision_events(content_version_id,event_type,actor_id,metadata) VALUES($1,$2,$3,$4)`,[version.versionId,current?'draft_revised':'draft_created',actorId,{source:'admin',kind:'ai_update'}]);return {...version,route}}
export async function createAiUpdateDraft(pool:Pool,raw:AiUpdateDraftInput,options:{actorId:string}){const input=normalize(raw);return transaction(pool,async tx=>{await owner(tx,options.actorId);const group=(await tx.query<{id:string}>(`INSERT INTO translation_groups(original_locale) VALUES($1) RETURNING id`,[input.locale])).rows[0]!.id;const contentId=(await tx.query<{id:string}>(`INSERT INTO contents(kind,translation_group_id,created_by) VALUES('ai_update',$1,$2) RETURNING id`,[group,options.actorId])).rows[0]!.id;const id=(await tx.query<{id:string}>(`INSERT INTO content_localizations(content_id,locale,source_locale,translation_status,title,summary,slug,route_scope) VALUES($1,$2,$2,'original',$3,$4,$5,'ai-update') RETURNING id`,[contentId,input.locale,input.title,input.summary,input.slug])).rows[0]!.id;await tx.query(`INSERT INTO ai_updates(localization_id,change_summary,official_updated_at,last_verified_at) VALUES($1,$2,$3,$4)`,[id,input.summary,input.officialUpdatedAt||null,input.lastVerifiedAt||null]);return {...{localizationId:id,contentId},...(await finalize(tx,id,input,options.actorId,null))}})}
export async function updateAiUpdateDraft(pool:Pool,id:string,raw:AiUpdateDraftInput,options:{actorId:string}){const input=normalize(raw);return transaction(pool,async tx=>{await owner(tx,options.actorId);const row=(await tx.query<{current_draft_version_id:string|null;current_published_version_id:string|null;slug:string}>(`SELECT cl.current_draft_version_id,cl.current_published_version_id,cl.slug FROM content_localizations cl JOIN contents c ON c.id=cl.content_id AND c.kind='ai_update' WHERE cl.id=$1 FOR UPDATE`,[id])).rows[0];if(!row)throw new Error('ai_update_not_found');if(row.current_published_version_id&&row.slug!==input.slug)throw new Error('published_slug_locked');await tx.query(`UPDATE ai_updates SET change_summary=$1,official_updated_at=$2,last_verified_at=$3 WHERE localization_id=$4`,[input.summary,input.officialUpdatedAt||null,input.lastVerifiedAt||null,id]);return {localizationId:id,...(await finalize(tx,id,input,options.actorId,row.current_draft_version_id))}})}
type Row={id:string;content_id:string;locale:'ko'|'en';title:string;summary:string;slug:string;updated_at:Date;version_id:string;version_number:number;canonical_document:DechiveDocument;migration_metadata:{aiUpdate?:Partial<AiUpdateDraftInput>};official_updated_at:Date|null;last_verified_at:Date|null;route:string};
export async function getAiUpdateDraft(pool:Pick<Pool,'query'>,id:string):Promise<AiUpdateDraft|null>{const row=(await pool.query<Row>(`SELECT cl.id,cl.content_id,cl.locale,cl.title,cl.summary,cl.slug,cl.updated_at,cv.id version_id,cv.version_number,cv.canonical_document,cv.migration_metadata,au.official_updated_at,au.last_verified_at,cr.route FROM content_localizations cl JOIN contents c ON c.id=cl.content_id AND c.kind='ai_update' JOIN ai_updates au ON au.localization_id=cl.id JOIN content_versions cv ON cv.id=cl.current_draft_version_id JOIN content_routes cr ON cr.localization_id=cl.id AND cr.is_canonical AND cr.active_until IS NULL WHERE cl.id=$1`,[id])).rows[0];if(!row)return null;const data=row.migration_metadata.aiUpdate??{};return {localizationId:row.id,contentId:row.content_id,versionId:row.version_id,versionNumber:Number(row.version_number),title:row.title,summary:row.summary,slug:row.slug,locale:row.locale,officialUpdatedAt:data.officialUpdatedAt??row.official_updated_at?.toISOString()??'',lastVerifiedAt:data.lastVerifiedAt??row.last_verified_at?.toISOString()??'',officialSources:Array.isArray(data.officialSources)?data.officialSources:[],document:row.canonical_document,route:row.route,updatedAt:row.updated_at.toISOString()}}
export async function listAiUpdateDrafts(pool:Pool){return (await pool.query(`SELECT cl.id,cl.title,cl.locale,cl.updated_at AS "updatedAt",cv.status,cv.version_number AS "versionNumber" FROM content_localizations cl JOIN contents c ON c.id=cl.content_id AND c.kind='ai_update' JOIN content_versions cv ON cv.id=cl.current_draft_version_id ORDER BY cl.updated_at DESC LIMIT 100`)).rows}
export async function getAiUpdatePublishState(pool:Pool,id:string):Promise<AiUpdatePublishState|null>{const draft=await getAiUpdateDraft(pool,id);if(!draft)return null;const published=(await pool.query<{id:string;version_number:number}>(`SELECT cv.id,cv.version_number FROM content_localizations cl JOIN content_versions cv ON cv.id=cl.current_published_version_id WHERE cl.id=$1`,[id])).rows[0];return {draftVersionId:draft.versionId,draftVersionNumber:draft.versionNumber,publishedVersionId:published?.id??null,publishedVersionNumber:published?Number(published.version_number):null,readiness:validateAiUpdatePublishReadiness(draft)}}
export async function publishAiUpdateDraft(pool:Pool,id:string,options:{actorId:string;failAfterPointer?:boolean}){return transaction(pool,async tx=>{await owner(tx,options.actorId);const draft=await getAiUpdateDraft(tx,id);if(!draft)throw new Error('ai_update_not_found');if(!validateAiUpdatePublishReadiness(draft).ready)throw new Error('publish_validation_failed');const previous=(await tx.query<{current_published_version_id:string|null}>(`SELECT current_published_version_id FROM content_localizations WHERE id=$1 FOR UPDATE`,[id])).rows[0]?.current_published_version_id??null;await tx.query(`UPDATE content_localizations SET current_published_version_id=$1,updated_at=now() WHERE id=$2`,[draft.versionId,id]);if(options.failAfterPointer)throw new Error('injected_publish_transaction_failure');await tx.query(`INSERT INTO revision_events(content_version_id,event_type,actor_id,metadata) VALUES($1,'published',$2,$3)`,[draft.versionId,options.actorId,{source:'admin',kind:'ai_update',previousPublishedVersionId:previous}]);return {localizationId:id,versionId:draft.versionId,slug:draft.slug,alreadyPublished:previous===draft.versionId}})}
