import { createHash } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import { createDatabase, LOCAL_TEST_DATABASE_URL } from '@/db/client';
import { isAuthorizedOwner } from '@/features/admin/owner-auth';
import { normalizeAnchors, plainText, type DechiveDocument } from '@/features/editor-lab/document';
import { validateDechiveDocument } from '@/features/editor-lab/security';
import { normalizeKnowledgeReferences, type KnowledgeReference, type KnowledgeOption } from '@/services/knowledge-drafts';

export const PRACTICE_OUTCOMES = ['verified','partially_verified','not_verified','failed','inconclusive'] as const;
export type PracticeOutcomeStatus = (typeof PRACTICE_OUTCOMES)[number];
export type PracticeDraftInput = { title:string; slug:string; locale:'ko'|'en'; summary:string; objective:string; outcomeStatus:PracticeOutcomeStatus; relatedKnowledgeId:string; references:KnowledgeReference[]; document:DechiveDocument };
export type PracticeDraft = PracticeDraftInput & { localizationId:string; contentId:string; versionId:string; versionNumber:number; route:string; updatedAt:string; relatedKnowledgeTitle:string | null; relatedKnowledgeSlug:string | null };
export type PracticePublishState = { draftVersionId:string; draftVersionNumber:number; publishedVersionId:string|null; publishedVersionNumber:number|null; readiness:ReturnType<typeof validatePracticePublishReadiness> };
const slugPattern=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
export const practiceCanonicalRoute=(slug:string)=>`/practice/${slug}`;
export function createPracticeAdminDatabase(){return createDatabase()}
export function createLocalPracticeDatabase(){return createDatabase(LOCAL_TEST_DATABASE_URL)}
function normalize(input:PracticeDraftInput){const title=input.title.trim(),slug=input.slug.trim(),summary=input.summary.trim(),objective=input.objective.trim();if(!title)throw new Error('title_required');if(!slugPattern.test(slug))throw new Error('slug_invalid');if(!summary)throw new Error('summary_required');if(!objective)throw new Error('objective_required');if(!PRACTICE_OUTCOMES.includes(input.outcomeStatus))throw new Error('outcome_status_invalid');const document=normalizeAnchors(input.document);const validation=validateDechiveDocument(document,'draft');if(validation.status==='rejected')throw new Error('document_invalid');return {title,slug,summary,objective,outcomeStatus:input.outcomeStatus,relatedKnowledgeId:input.relatedKnowledgeId.trim(),references:normalizeKnowledgeReferences(input.references),document,validation,status:validation.status==='needs_review'?'needs_review':'draft' as const,locale:input.locale}}
export function validatePracticePublishReadiness(input:PracticeDraftInput){const errors:string[]=[];let value:ReturnType<typeof normalize>|undefined;try{value=normalize(input)}catch(error){errors.push(error instanceof Error?error.message:'practice_invalid')}if(value){if(!plainText(value.document))errors.push('body_required');const published=validateDechiveDocument(value.document,'publish');errors.push(...published.issues.filter(i=>i.severity==='error'||i.severity==='review').map(i=>i.code))}return {blockingErrors:[...new Set(errors)],warnings:[],ready:errors.length===0}}
async function transaction<T>(pool:Pool,run:(tx:PoolClient)=>Promise<T>){const tx=await pool.connect();try{await tx.query('BEGIN');const value=await run(tx);await tx.query('COMMIT');return value}catch(error){await tx.query('ROLLBACK');throw error}finally{tx.release()}}
async function owner(tx:PoolClient,actorId:string){if(!(await isAuthorizedOwner(tx,actorId)))throw new Error('admin_access_denied')}
async function relatedContentId(tx:PoolClient,localizationId:string){if(!localizationId)return null;const row=(await tx.query<{content_id:string}>(`SELECT cl.content_id FROM content_localizations cl JOIN contents c ON c.id=cl.content_id AND c.kind='knowledge' WHERE cl.id=$1`,[localizationId])).rows[0];if(!row)throw new Error('knowledge_reference_invalid');return row.content_id}
async function insertVersion(tx:PoolClient,id:string,input:ReturnType<typeof normalize>,actorId:string,current:string|null){const number=Number((await tx.query(`SELECT coalesce(max(version_number),0)+1 AS next FROM content_versions WHERE localization_id=$1`,[id])).rows[0].next);const versionId=(await tx.query<{id:string}>(`INSERT INTO content_versions(localization_id,version_number,schema_version,canonical_document,status,revision_summary,changed_fields,created_by,supersedes_version_id,migration_metadata,document_checksum,validation_status,validation_warnings) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id`,[id,number,input.document.schemaVersion,input.document,input.status,`practice draft ${number===1?'created':'revised'}`,JSON.stringify(['title','slug','summary','objective','outcomeStatus','relatedKnowledge','body','references']),actorId,current,{practice:{title:input.title,slug:input.slug,summary:input.summary,objective:input.objective,outcomeStatus:input.outcomeStatus,references:input.references}},digest(input.document),input.validation.status,JSON.stringify(input.validation.issues.map(i=>i.code))])).rows[0]!.id;return {versionId,versionNumber:number}}
async function finalize(tx:PoolClient,id:string,input:ReturnType<typeof normalize>,actorId:string,current:string|null){const saved=await insertVersion(tx,id,input,actorId,current);const route=practiceCanonicalRoute(input.slug);if((await tx.query(`SELECT 1 FROM content_routes WHERE route=$1 AND localization_id<>$2 AND active_until IS NULL`,[route,id])).rowCount)throw new Error('route_conflict');await tx.query(`UPDATE content_localizations SET title=$1,summary=$2,slug=$3,current_draft_version_id=$4,updated_at=now() WHERE id=$5`,[input.title,input.summary,input.slug,saved.versionId,id]);if(current)await tx.query(`UPDATE content_routes SET route=$1 WHERE localization_id=$2 AND is_canonical AND active_until IS NULL`,[route,id]);else await tx.query(`INSERT INTO content_routes(localization_id,route,route_type,is_canonical) VALUES($1,$2,'cms_draft',true)`,[id,route]);await tx.query(`INSERT INTO revision_events(content_version_id,event_type,actor_id,metadata) VALUES($1,$2,$3,$4)`,[saved.versionId,current?'draft_revised':'draft_created',actorId,{source:'admin',kind:'practice'}]);return {...saved,route}}
export async function createPracticeDraft(pool:Pool,raw:PracticeDraftInput,options:{actorId:string}){const input=normalize(raw);return transaction(pool,async tx=>{await owner(tx,options.actorId);const group=(await tx.query<{id:string}>(`INSERT INTO translation_groups(original_locale) VALUES($1) RETURNING id`,[input.locale])).rows[0]!.id;const contentId=(await tx.query<{id:string}>(`INSERT INTO contents(kind,translation_group_id,created_by) VALUES('practice',$1,$2) RETURNING id`,[group,options.actorId])).rows[0]!.id;const id=(await tx.query<{id:string}>(`INSERT INTO content_localizations(content_id,locale,source_locale,translation_status,title,summary,slug,route_scope) VALUES($1,$2,$2,'original',$3,$4,$5,'practice') RETURNING id`,[contentId,input.locale,input.title,input.summary,input.slug])).rows[0]!.id;await tx.query(`INSERT INTO practices(localization_id,practice_type,objective,evaluation_criteria,completion_mode,outcome_status,related_knowledge_id) VALUES($1,'application_record',$2,'[]','documented',$3,$4)`,[id,input.objective,input.outcomeStatus,await relatedContentId(tx,input.relatedKnowledgeId)]);return {...{localizationId:id,contentId},...(await finalize(tx,id,input,options.actorId,null))}})}
export async function updatePracticeDraft(pool:Pool,id:string,raw:PracticeDraftInput,options:{actorId:string}){const input=normalize(raw);return transaction(pool,async tx=>{await owner(tx,options.actorId);const row=(await tx.query<{current_draft_version_id:string|null;current_published_version_id:string|null;slug:string}>(`SELECT cl.current_draft_version_id,cl.current_published_version_id,cl.slug FROM content_localizations cl JOIN contents c ON c.id=cl.content_id AND c.kind='practice' WHERE cl.id=$1 FOR UPDATE`,[id])).rows[0];if(!row)throw new Error('practice_not_found');if(row.current_published_version_id&&row.slug!==input.slug)throw new Error('published_slug_locked');await tx.query(`UPDATE practices SET objective=$1,outcome_status=$2,related_knowledge_id=$3 WHERE localization_id=$4`,[input.objective,input.outcomeStatus,await relatedContentId(tx,input.relatedKnowledgeId),id]);return {localizationId:id,...(await finalize(tx,id,input,options.actorId,row.current_draft_version_id))}})}
type PracticeDraftRow={id:string;content_id:string;locale:'ko'|'en';title:string;summary:string;slug:string;updated_at:Date;version_id:string;version_number:number;canonical_document:DechiveDocument;migration_metadata:{practice?:{references?:KnowledgeReference[]}};objective:string;outcome_status:PracticeOutcomeStatus|null;related_knowledge_id:string|null;related_localization_id:string|null;related_title:string|null;related_slug:string|null;route:string};
export async function getPracticeDraft(pool:Pick<Pool,'query'>,id:string):Promise<PracticeDraft|null>{const row=(await pool.query<PracticeDraftRow>(`SELECT cl.id,cl.content_id,cl.locale,cl.title,cl.summary,cl.slug,cl.updated_at,cv.id version_id,cv.version_number,cv.canonical_document,cv.migration_metadata,p.objective,p.outcome_status,p.related_knowledge_id,related.id related_localization_id,related.title related_title,related.slug related_slug,cr.route FROM content_localizations cl JOIN contents c ON c.id=cl.content_id AND c.kind='practice' JOIN practices p ON p.localization_id=cl.id JOIN content_versions cv ON cv.id=cl.current_draft_version_id JOIN content_routes cr ON cr.localization_id=cl.id AND cr.is_canonical AND cr.active_until IS NULL LEFT JOIN content_localizations related ON related.content_id=p.related_knowledge_id AND related.locale=cl.locale WHERE cl.id=$1`,[id])).rows[0];if(!row)return null;const metadata=row.migration_metadata?.practice??{};return {localizationId:row.id,contentId:row.content_id,versionId:row.version_id,versionNumber:Number(row.version_number),title:row.title,slug:row.slug,locale:row.locale,summary:row.summary,objective:row.objective,outcomeStatus:row.outcome_status??'inconclusive',relatedKnowledgeId:row.related_localization_id??'',relatedKnowledgeTitle:row.related_title??null,relatedKnowledgeSlug:row.related_slug??null,references:Array.isArray(metadata.references)?metadata.references:[],document:row.canonical_document,route:row.route,updatedAt:new Date(row.updated_at).toISOString()}}
export async function listPracticeDrafts(pool:Pool){return (await pool.query(`SELECT cl.id,cl.title,cl.locale,cl.updated_at AS "updatedAt",cv.status,cv.version_number AS "versionNumber" FROM content_localizations cl JOIN contents c ON c.id=cl.content_id AND c.kind='practice' JOIN content_versions cv ON cv.id=cl.current_draft_version_id ORDER BY cl.updated_at DESC LIMIT 100`)).rows}
export async function getPracticePublishState(pool:Pool,id:string):Promise<PracticePublishState|null>{const draft=await getPracticeDraft(pool,id);if(!draft)return null;const published=(await pool.query<{id:string;version_number:number}>(`SELECT cv.id,cv.version_number FROM content_localizations cl JOIN content_versions cv ON cv.id=cl.current_published_version_id WHERE cl.id=$1`,[id])).rows[0];return {draftVersionId:draft.versionId,draftVersionNumber:draft.versionNumber,publishedVersionId:published?.id??null,publishedVersionNumber:published?Number(published.version_number):null,readiness:validatePracticePublishReadiness(draft)}}
export async function publishPracticeDraft(pool:Pool,id:string,options:{actorId:string;failAfterPointer?:boolean}){return transaction(pool,async tx=>{await owner(tx,options.actorId);const draft=await getPracticeDraft(tx,id);if(!draft)throw new Error('practice_not_found');const readiness=validatePracticePublishReadiness(draft);if(!readiness.ready)throw new Error('publish_validation_failed');if(draft.relatedKnowledgeId){const related=await tx.query(`SELECT 1 FROM content_localizations cl JOIN contents c ON c.id=cl.content_id AND c.kind='knowledge' WHERE cl.id=$1 AND cl.current_published_version_id IS NOT NULL`,[draft.relatedKnowledgeId]);if(!related.rowCount)throw new Error('knowledge_reference_invalid')}const pointer=(await tx.query<{current_published_version_id:string|null}>(`SELECT current_published_version_id FROM content_localizations WHERE id=$1 FOR UPDATE`,[id])).rows[0]?.current_published_version_id??null;await tx.query(`UPDATE content_localizations SET current_published_version_id=$1,updated_at=now() WHERE id=$2`,[draft.versionId,id]);if(options.failAfterPointer)throw new Error('injected_publish_transaction_failure');await tx.query(`INSERT INTO revision_events(content_version_id,event_type,actor_id,metadata) VALUES($1,'published',$2,$3)`,[draft.versionId,options.actorId,{source:'admin',kind:'practice',previousPublishedVersionId:pointer}]);return {localizationId:id,versionId:draft.versionId,slug:draft.slug,alreadyPublished:pointer===draft.versionId,warnings:[] as string[]}})}
export { type KnowledgeOption };
