import type { Pool } from 'pg';
import { createDatabase } from '@/db/client';
import type { DechiveDocument } from '@/features/editor-lab/document';
import type { KnowledgeReference } from '@/services/knowledge-drafts';
import type { PracticeOutcomeStatus } from '@/services/practice-drafts';
export function createPublishedPracticeDatabase(){return createDatabase()}
export type PublishedPracticeListItem={id:string;slug:string;title:string;summary:string;outcomeStatus:PracticeOutcomeStatus;publishedAt:string;relatedKnowledge:{title:string;slug:string}|null};
export type PublishedPractice=PublishedPracticeListItem&{objective:string;document:DechiveDocument;references:KnowledgeReference[];updatedAt:string};
type Row={id:string;slug:string;title:string;summary:string;outcome_status:PracticeOutcomeStatus;created_at:Date;updated_at:Date;objective:string;canonical_document:DechiveDocument;migration_metadata:{practice?:{title?:string;summary?:string;objective?:string;outcomeStatus?:PracticeOutcomeStatus;references?:KnowledgeReference[]}};related_title:string|null;related_slug:string|null};
const base=`FROM content_localizations cl JOIN contents c ON c.id=cl.content_id AND c.kind='practice' JOIN content_versions cv ON cv.id=cl.current_published_version_id JOIN practices p ON p.localization_id=cl.id LEFT JOIN content_localizations related ON related.content_id=p.related_knowledge_id AND related.locale=cl.locale AND related.current_published_version_id IS NOT NULL WHERE cl.route_scope='practice'`;
function project(row:Row):PublishedPracticeListItem{const metadata=row.migration_metadata?.practice??{};return {id:row.id,slug:row.slug,title:metadata.title??row.title,summary:metadata.summary??row.summary,outcomeStatus:metadata.outcomeStatus??row.outcome_status,publishedAt:row.created_at.toISOString(),relatedKnowledge:row.related_title&&row.related_slug?{title:row.related_title,slug:row.related_slug}:null}}
export async function listPublishedPractices(pool:Pool):Promise<PublishedPracticeListItem[]>{const rows=await pool.query<Row>(`SELECT cl.id,cl.slug,cl.title,cl.summary,cv.created_at,cl.updated_at,p.outcome_status,p.objective,cv.canonical_document,cv.migration_metadata,related.title related_title,related.slug related_slug ${base} ORDER BY cv.created_at DESC,cl.slug ASC`);return rows.rows.map(project)}
export async function getPublishedPractice(pool:Pool,slug:string):Promise<PublishedPractice|null>{const row=(await pool.query<Row>(`SELECT cl.id,cl.slug,cl.title,cl.summary,cv.created_at,cl.updated_at,p.outcome_status,p.objective,cv.canonical_document,cv.migration_metadata,related.title related_title,related.slug related_slug ${base} AND cl.slug=$1`,[slug])).rows[0];if(!row)return null;return {...project(row),objective:row.migration_metadata?.practice?.objective??row.objective,document:row.canonical_document,references:Array.isArray(row.migration_metadata?.practice?.references)?row.migration_metadata.practice.references:[],updatedAt:row.updated_at.toISOString()}}
