import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { Pool } from 'pg';
import { inspectConnectionPair, loadStagingEnvironment, safeError } from './env';

const restoreDatabase='dechive_stage15_restore';
const restoreUrl=`postgresql://dechive:dechive_local_only@127.0.0.1:55432/${restoreDatabase}`;
const tables=['schema_migrations','actors','external_identities','actor_role_memberships','contents','content_localizations','content_versions','knowledge_details','content_relations','content_routes','revision_events'];
function processErrorCode(error:Error|undefined){return error&&'code' in error?String(error.code):undefined}
function run(command:string,args:string[],environment?:NodeJS.ProcessEnv){const result=spawnSync(command,args,{encoding:'utf8',env:environment??process.env,stdio:['ignore','pipe','pipe'],timeout:120_000});if(result.status!==0)throw new Error(`backup_command_failed:${command}:${processErrorCode(result.error)??result.signal??result.status??'unknown'}`)}
function createDump(url:string){const result=spawnSync('docker',['run','--rm','-e','STAGE15_DATABASE_URL','postgres:17.6-alpine','sh','-c','pg_dump --dbname="$STAGE15_DATABASE_URL" --format=custom --no-owner --no-acl'],{env:{...process.env,STAGE15_DATABASE_URL:url},stdio:['ignore','pipe','pipe'],timeout:120_000,maxBuffer:20*1024*1024});if(result.status!==0){const detail=String(result.stderr);const category=/version mismatch/i.test(detail)?'version_mismatch':/certificate|ssl/i.test(detail)?'ssl_failure':/translate host|name resolution/i.test(detail)?'dns_failure':/authentication|password/i.test(detail)?'authentication_failure':/connection/i.test(detail)?'connection_failure':'unknown';throw new Error(`backup_command_failed:docker:${category}`)}return result.stdout as Buffer}
async function snapshot(pool:Pool){const counts:Record<string,number>={};for(const table of tables)counts[table]=Number((await pool.query(`SELECT count(*) FROM ${table}`)).rows[0]?.count??0);const data=(await pool.query(`SELECT
 (SELECT string_agg(name||':'||checksum,',' ORDER BY name) FROM schema_migrations) AS migrations,
 (SELECT string_agg(id::text||':'||document_checksum,',' ORDER BY id) FROM content_versions) AS versions,
 (SELECT string_agg(id::text||':'||coalesce(current_draft_version_id::text,'')||':'||coalesce(current_published_version_id::text,''),',' ORDER BY id) FROM content_localizations) AS pointers,
 (SELECT string_agg(route,',' ORDER BY route) FROM content_routes) AS routes`)).rows[0];return {counts,checksum:createHash('sha256').update(JSON.stringify(data)).digest('hex')}}
async function main(){let cloud:Pool|undefined;let restored:Pool|undefined;try{const environment=await loadStagingEnvironment();const pair=inspectConnectionPair(environment.pooled,environment.direct);if(!pair.pooledMarker||!pair.directMarker||!pair.sameEndpoint||!pair.sslRequired)throw new Error('blocked_target_not_proven_safe');const output=path.resolve('fixtures/staging-import/output');await mkdir(output,{recursive:true});const dump=path.join(output,'stage15-pre-0004.dump');const bytes=createDump(environment.direct);if(bytes.length<1024)throw new Error('blocked_backup_empty');await writeFile(dump,bytes,{mode:0o600});const dumpChecksum=createHash('sha256').update(bytes).digest('hex');run('docker',['compose','-f','docker-compose.db.yml','exec','-T','postgres','dropdb','-U','dechive','--if-exists',restoreDatabase]);run('docker',['compose','-f','docker-compose.db.yml','exec','-T','postgres','createdb','-U','dechive',restoreDatabase]);run('docker',['compose','-f','docker-compose.db.yml','cp',dump,`postgres:/tmp/stage15-pre-0004.dump`]);run('docker',['compose','-f','docker-compose.db.yml','exec','-T','postgres','pg_restore','-U','dechive','-d',restoreDatabase,'--no-owner','--no-acl','--single-transaction','--exit-on-error','/tmp/stage15-pre-0004.dump']);cloud=new Pool({connectionString:environment.pooled,max:1,connectionTimeoutMillis:10_000});restored=new Pool({connectionString:restoreUrl,max:1,connectionTimeoutMillis:5_000});const before=await snapshot(cloud),after=await snapshot(restored);assert.deepEqual(after,before);const report={status:'stage15_pre_0004_backup_restored',source:'Neon staging',target:'isolated local PostgreSQL',format:'PostgreSQL 17 custom',dumpChecksum,counts:before.counts,countsEqual:true,integrityChecksumEqual:true,secretsIncluded:false,productionUsed:false};await writeFile(path.join(output,'stage15-backup-report.json'),`${JSON.stringify(report,null,2)}\n`,{mode:0o600});console.log(`Stage 15 backup: ${tables.length} table counts and integrity checksum restored exactly; secrets excluded`)}catch(error){const reason=error instanceof Error&&error.message.startsWith('blocked_')?error.message:error instanceof Error&&error.message.startsWith('backup_command_failed')?error.message:safeError(error);console.error(`Stage 15 backup: ${reason}; credentials redacted`);process.exitCode=2}finally{await cloud?.end().catch(()=>undefined);await restored?.end().catch(()=>undefined)}}
void main();
